---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install SELinux
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ selinux_packages }}"

- name: Enable SELinux in configuration
  selinux:
    policy: "{{ selinux_policy }}"
    state: enforcing
  when: selinux_enabled

- name: Disable SELinux
  selinux:
    state: disabled
  when: not selinux_enabled
